// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krdaxhcypgjvbpealmyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyZGF4aGN5cGdqdmJwZWFsbXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODY2MzksImV4cCI6MjA2OTQ2MjYzOX0.rHYhOjTKVmxfcrN7xqyT1HtPTXOYxuIZCDsNNlKX1t0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});